// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"database/sql"
)

type Dictionary struct {
	Word       string
	Exp        string
	Lang       string
	Translator string
	Context    sql.NullString
}

type Kvstore struct {
	Key   string
	Value string
}
