// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

type Dictionary struct {
	Word string
	Exp  string
	Api  string
}

type Kvstore struct {
	Key   string
	Value string
}
